# Softmax Classifier

In [23]:
import tensorflow as tf
import numpy as np

In [5]:
x_data=[[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data=[[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

#numpy flaot format으로 변환
x_data=np.asarray(x_data,dtype=np.float32)
y_data=np.asarray(y_data,dtype=np.float32)

nb_classes=3 #num classes - ONE-HOT ENCODING

## Softmax funiton

- xW=y
- y score를 구한 이후에 softmax 지나면 확률이 나옴.
- 확률값으로 변환하는 과정이기 때문에 전체 확률의 합은 1이 나와야 함.

In [12]:
# Weight와 bias값 setting. 강의에서는 eager 사용했지만,
# 나는 그냥 tensorflow에서 생성함
W=tf.Variable(tf.random.normal([4,nb_classes]), name='weight')
b=tf.Variable(tf.random.normal([nb_classes]), name='bias')
variables=[W,b]

In [13]:
hypothesis=tf.nn.softmax(tf.matmul(x_data,W)+b)

In [18]:
#Softmax onehot test
sample_db=[[8,2,1,4]]
sample_db=np.asarray(sample_db,dtype=np.float32)


## Cost function

In [19]:
def cost_fn(X,Y):
    logits=hypothesis(X)
    cost=-tf.reduce_sum(Y*tf.log(logits),axis=1)
    cost_mean=tf.reduce_mean(cost)
    return cost_mean

print(cost_fn(x_data,y_data))

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable

## Gradient Function

In [24]:
def grad_fn(X,Y):
    with tf.GradientTape()

SyntaxError: invalid syntax (<ipython-input-24-c2024a4b02f5>, line 2)

# 유튜브 댓글

In [26]:
import tensorflow as tf
import numpy as np

x_data = [[1, 2, 1, 1],
 [2, 1, 3, 2],
 [3, 1, 3, 4],
 [4, 1, 5, 5],
 [1, 7, 5, 5],
 [1, 2, 5, 6],
 [1, 6, 6, 6],
 [1, 7, 7, 7]]
y_data = [[0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 0],
 [0, 1, 0],
 [1, 0, 0],
 [1, 0, 0]]
# 3개의 클래스 분류할때 0,1,2 를 각각 [1,0,0] , [0,1,0], [0,0,1]로 하나만 hot하게 표시함 
x_data = np.asarray(x_data, dtype = np.float32)
y_data = np.asarray(y_data, dtype = np.float32)

#y의 개수 = 클래스 개수 = label개수
dataset = tf.data.Dataset.from_tensor_slices((x_data, y_data)).batch(len(x_data))
W = tf.Variable(tf.random.normal([4,3], name='weight'))
b = tf.Variable(tf.random.normal([3]),name = 'bias')
variable = [W, b]

dataset.element_spec


def softmax_fn (features):
    hypothesis = tf.nn.softmax(tf.matmul(features,W)+b)
    return hypothesis

def loss_fn (features, labels):
    hypothesis = tf.nn.softmax(tf.matmul(features,W)+b)
    cost = tf.reduce_mean(-tf.reduce_sum(y_data * tf.math.log(hypothesis), axis =1))
    return cost

def grad (hypothesis, features, labels):
    with tf.GradientTape() as tape:
        loss_value = loss_fn(features, labels)
    return tape.gradient(loss_value, [W, b])

optimizer = tf.keras.optimizers.SGD(learning_rate = 0.01)
   
n_epochs = 3000
for step in range(n_epochs + 1):
    
    for features, labels in iter(dataset):
        hypothesis = softmax_fn (features)
        grads = grad(hypothesis, features, labels)
        optimizer.apply_gradients(grads_and_vars = zip(grads, [W, b]))
    
    if step % 300 == 0:
            print("iter: {}, Loss: {:.4f}".format(step, loss_fn(features, labels)))
            
a = x_data
a = softmax_fn (a)
print(hypothesis) #softmax 함수를 통과시킨 x_data

#argmax 가장큰 값의index를 찾아줌

print(tf.argmax(a,1)) #가설을 통한 예측값
print(tf.argmax(y_data,1)) #실제 값

iter: 0, Loss: 5.3820
iter: 300, Loss: 0.8459
iter: 600, Loss: 0.6559
iter: 900, Loss: 0.5770
iter: 1200, Loss: 0.5320
iter: 1500, Loss: 0.5010
iter: 1800, Loss: 0.4773
iter: 2100, Loss: 0.4580
iter: 2400, Loss: 0.4415
iter: 2700, Loss: 0.4270
iter: 3000, Loss: 0.4140
tf.Tensor(
[[0.01463074 0.05292757 0.93244165]
 [0.02270989 0.18512924 0.79216087]
 [0.00162336 0.3832383  0.6151384 ]
 [0.00135817 0.6461154  0.35252643]
 [0.5552897  0.40463406 0.04007627]
 [0.27630192 0.7193284  0.00436971]
 [0.61134183 0.38377255 0.00488559]
 [0.69741994 0.30161342 0.00096665]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 0 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


# Lab 06-2

In [27]:
# Cross entropy cost
cost_i=tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits, labels=Y_one_hot)
cost=tf.reduce_mean(cost_i)

AttributeError: module 'tensorflow_core._api.v2.nn' has no attribute 'softmax_cross_entropy_with_logits_v2'

- 아무튼 with logits이 이용된다

# Sample Dataset
어떤 동물인지 예측하는 것

In [28]:
xy=np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data=xy[:, 0:-1]
y_data=xy[:, [-1]]

OSError: data-04-zoo.csv not found.

파일 받아야 하는데....